### ISSUE TITLE
Working with time-dependent control Hamiltonians

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#11]
Can Juqbox optimize the case where the control Hamiltonian time dependence is nonlinear, such as the following trapped ion Hamiltonian?

![Screenshot from 2021-06-30 11-40-52](https://user-images.githubusercontent.com/45339774/123990774-14135600-d998-11eb-9b72-793fd8c543d6.png)

**Comment by andersp** [comment]
Which coefficients depend on time? Omega, eta and phi? Is eta small?

**Comment by jasonchadwick** [comment]
Omega is the control amplitude that is time dependent, the rest of the parameters can be held constant if it's easier (but there is still time dependence in the exponentials and I'm not sure how to implement this in Juqbox, because Juqbox expects constant matrices for Hsym_ops, Hanti_ops, Hunc_ops)

**Comment by andersp** [comment]
You can Taylor expand the exp() function. If eta is small you may only need the first two terms.
