### ISSUE TITLE
Subsystem ordering in vectors

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#15]
In `examples/cnot3-setup.jl`, the `Ne` and `Ng` vectors, as well as the `Hsym_ops` vector, are ordered such that the numbers correspond to the order `[fa, fb, fs]`. However, the `maxpar` vector is `[0.05, 0.1, 0.1]` which seems to be ordered `[fs, fa, fb]` instead. Is this correct?

**Comment by andersp** [comment]
The maxpar vector is ordered in the same way as the other vectors, i.e. [a, b, s], where 'a' and 'b' are qudits and 's' stands for the storage resonator. In this case, the max amplitudes mimic the frequency dependence in the transfer function between the warm and cold sides.
