### ISSUE TITLE
Parallelism?

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#16]
Can Juqbox be set up to take advantage of multiple cores at the same time? The original Ipopt package seems to have some options for this, depending on the linear solver used, but I can't figure out how to get it to work with the Ipopt.jl package.

**Comment by andersp** [comment]
There is currently no support for parallel execution in Juqbox.jl. If you want to explore this, the easiest would be to propagate the different initial conditions in the basis on different cores, and use MPI to gather the contributions to the objective function and gradient.

**Comment by jasonchadwick** [comment]
It seems like [Ipopt](https://coin-or.github.io/Ipopt/OPTIONS.html#OPT_WSMP_Linear_Solver) can do some parallelism in their linear solver if it is compiled to support it (based on choice of linear solver - Pardiso and WSMP seem to support multiple threads). Is there any relatively simple way to enable these options?

**Comment by andersp** [comment]
The time spent in Ipopt is only a small fraction of the total simulation time, so running Ipopt on several threads will not make any significant difference. Pardiso was briefly used as a linear solver in Juqbox, within the time-stepping routine. Last summer, it was replaced by a Neumann iteration, which is significantly faster.
The most time consuming part of the algorithm is to calculate the objective function and its gradient. One way of speeding that up would be to run different initial conditions on different cores, using MPI to gather the results. In principle, this is straightforward, but would require non-trivial modifications of the code.

**Comment by jasonchadwick** [comment]
I'll look into it, thanks!
