### ISSUE TITLE
om[] with different number of columns

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#19]
Consider frequencies in Pg. 6 of https://arxiv.org/pdf/2106.14310.pdf:

![image](https://user-images.githubusercontent.com/32973443/129126306-3807b51b-50f6-4129-b3c6-4463d54cc1cc.png)

Let’s say we want to keep the first 2 frequencies for Omega_1 and first 5 frequencies for Omega_2. So, first row of om[] will have 2 columns and second row of om[] will have 5 columns. Is it possible to form such om[] in Juqbox? Do number of columns have to be equal for each row? If they have to be equal, how should we construct the last 3 columns of the first row? Keeping number of frequencies low is ideal not to make optimization harder than it is supposed to be.

**Comment by andersp** [comment]
The trick is to enter some phony frequencies for Omega_1 to make both sets of frequencies get the same number of elements. Then set zero bounds for the phony ones. Use this function to assign the bounds: 
minCoeff, maxCoeff = assign_thresholds_ctrl_freq(params, D1, maxamp)
IpOpt will eliminate the degrees of freedom with bounds = 0, i.e. they will not be part of the optimization.

**Comment by relugzosiraba** [comment]
Ok, I will try assign_thresholds_ctrl_freq. Should I still use assign_thresholds or assign_thresholds_freq together with assign_thresholds_ctrl_freq? Or would assign_thresholds_ctrl_freq be enough?

**Comment by andersp** [comment]
The return values (minCoeff, maxCoeff) are passed into setup_ipopt_problem(). It is the last assignment of these arrays that matter.
