### ISSUE TITLE
FFT symmetry

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#20]
Here is a lab-frame spectrum for an optimal signal calculated via Juqbox. Does negative side of the spectrum contain any new information or can those be ignored since the spectrum is symmetric with respect to the y axis?

![Spec1](https://user-images.githubusercontent.com/32973443/136300970-c3759f3f-cdca-4879-8bdb-e44ef61a2a96.png)

**Comment by andersp** [comment]
I assume you compute the discrete Fourier transform (DFT) with Julia's fft function from the FFTW package. This function calculates the complex-valued DFT, which is defined for frequencies of both signs. If the signal is real-valued in the time domain, the DFT will satisfy certain symmetry properties in the frequency domain. The DFT is explained in detail on Wikipedia.
