### ISSUE TITLE
Set max control amplitude in lab frame?

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#3]
How do I specify the maximum control amplitude in the lab frame? It seems that `maxpar` in `calculate_timestep` and `assign_thresholds` is assumed to be in the rotating frame.

**Comment by andersp** [comment]
You can estimate the max control amplitude in the lab frame, but the actual max amplitude depends on constructive/destructive interference between the carrier frequency and the frequency of rotation.

**Comment by jasonchadwick** [comment]
To clarify: if I want to set a bound for the control amplitude (in the lab frame) at a certain value, how would I set this constraint in Juqbox?

**Comment by fortinog** [comment]
As Anders mentioned, the actual max amplitude in the lab frame depends on constructive/destructive interference and is difficult to add in as a constraint through IPOPT. The fastest, and perhaps simplest, way around this is to bound the parameters in the rotating frame to ensure the lab frame doesn't exceed a value you specify. If we let <img src="https://render.githubusercontent.com/render/math?math=N_{f}"> be the number of carrier wave frequencies and <img src="https://render.githubusercontent.com/render/math?math=M"> be the maximum lab frame control amplitude (in GHz), then a bound that would give you the desired maximum lab frame bound would be 

<img src="https://render.githubusercontent.com/render/math?math=|\alpha_\text{max}| \le \frac{\pi}{2N_f}M">

where <img src="https://render.githubusercontent.com/render/math?math=\alpha_\text{max}"> is what you would specify as ``maxpar``.

In code this means doing something like this:
```
# max 30 MHz lab frame amplitude
max_lab = 30*1e-3
maxpar = pi*max_lab/(2*Nfreq)
```

I'll point out that this bound is likely pessimistic, and also assumes that you constrain the parameter values for each carrier wave by the same upper bound. Let me know if this helps!

**Comment by jasonchadwick** [comment]
That's helpful, thanks!
