### ISSUE TITLE
Dual infeasibility vs gate fidelity

### ISSUE THREAD

**Issue by jasonchadwick** [LLNL/Juqbox.jl#4]
Juqbox allows you to specify the convergence goal for dual infeasibility with `ipTol`; is there a way to instead iterate until reaching a goal gate fidelity?

**Comment by andersp** [comment]
@jasonchadwick It is possible to make ipopt terminate after the trace infidelity falls below a given value. By default this threshold is set to zero. To set it to some other (positive) value, you first have to build the params object by calling 
params = objparams() 
If you want the threshold to be 1e-4, you then say
params.traceInfidelityThreshold = 1e-4
