### ISSUE TITLE
Trace (in)fidelity

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#6]
What does “trace fidelity” show? The fidelity of the matrix consisting of only essential levels or the fidelity of the whole matrix including guard levels?

**Comment by andersp** [comment]
Trace fidelity = |Tr(U^dag V)/E|^2. 
Infidelity = 1 - fidelity
Here U and V are (N x E) matrices, so all levels are accounted for. However, the target matrix (V) is always zero for the guard levels. Look in our paper on arXiv for further details.

**Comment by relugzosiraba** [comment]
By "the target matrix (V) is always zero for the guard levels", do you mean that the corresponding elements are zero? It shouldn't be the matrix itself...

**Comment by andersp** [comment]
The corresponding **rows** of the matrix V are always zero

**Comment by relugzosiraba** [comment]
Why do V and U in Eq. (13) [here](https://www.osti.gov/servlets/purl/1777332/ ) are N-by-N? No guard levels considered? But it seems that leakage is taken into account.

**Comment by andersp** [comment]
There are several ways of writing the fidelity. In that report we use a matrix P of size NxE that inflates a state vector with E essential levels to size N,  by inserting zeros at all guard levels. As a result U-tilde = P-dagger U P is of size ExE. Note that there is a typo in Eqn. (13). The factor in front of the trace should be 1/ E^2. In this case, E=4.

**Comment by relugzosiraba** [comment]
There is also typo in Eq. (11) [there](https://www.osti.gov/servlets/purl/1777332/), right? It should be C^{4 x 4}

**Comment by andersp** [comment]
Obviously
