### ISSUE TITLE
Choosing lbfgsMax

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#7]
How should we choose lbfgsMax? If it is large, will more memory be used but the job will run faster?

**Comment by andersp** [comment]
Please post your questions under “issues” on the Juqbox github page

From: "A. Barış Özgüler" ***@***.***>
Reply-To: "LLNL/Juqbox.jl" ***@***.***>
Date: Tuesday, June 22, 2021 at 12:36 PM
To: "LLNL/Juqbox.jl" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LLNL/Juqbox.jl] Choosing lbfgsMax (#7)


How should we choose lbfgsMax? If it is large, will more memory be used but the job will run faster?

**Comment by andersp** [comment]
Most users will never need to change the default value of this parameter. Increasing lbfgsMax will increase memory requirements and usually makes the code run slightly slower.
