### ISSUE TITLE
Control runtime

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#8]
In Juqbox, can you control runtime so that optimization terminates with an output even if the optimization does not converge? I am looking for something like the following: If classical computation time is too large, then terminate optimization and store output after a certain time. It is possible to do it with “number of iterations” but I am curious if there is a parameter choice for runtime too.

**Comment by andersp** [comment]
This is currently not an option. A similar outcome can be achieved by setting the maximum number of iterations
