### ISSUE TITLE
Pmin, calculate_timestep() and samplerate

### ISSUE THREAD

**Issue by relugzosiraba** [LLNL/Juqbox.jl#9]
How should we choose `Pmin`? 

Is `samplerate` for plots related to `calculate_timestep()`? They seem to be not directly related. What does `samplerate` represent for plots? Where do we takes "samples" from?

**Comment by andersp** [comment]
The samplerate parameter only controls the resolution in plots. The rate equals the number of samples per nano sec.

**Comment by relugzosiraba** [comment]
Thanks. 

How should we choose Pmin? Could you point to the paper?

**Comment by andersp** [comment]
Pmin is used to specify the number of time steps per shortest period in the state vector.
In many cases Pmin=40 keeps the time-stepping of Schroedinger's equation sufficiently accurate . Once you find a converged solution, you can test the time stepping accuracy by setting Pmin=80 and just evaluating the objective function with the same control functions. The gate infidelity and the evolution of populations should not change in any significant way. If they do, you need to increase Pmin.
